stages:
  - test

cache:
  key: bundler-cache
  paths:
    - vendor/bundle

.test:
  before_script:
    - bundle config path `pwd`/vendor/bundle
    - bundle config without development_extra
  script:
    - bundle update
    - bundle exec rspec
    - bundle update --gemfile=Gemfile.lowest
    - bundle exec rspec

test:
  extends: .test
  stage: test
  image: ruby:${RUBY_VERSION}
  parallel:
    matrix:
      - RUBY_VERSION:
          - '2.3' # lowest version
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'latest' # latest
